global:
  defaultServicePorts:
  - number: 9080
    name: http
    protocol: HTTP
  useOpenshiftRouter: true
  local:
    export:
    - hostname: ratings.mesh.global
      # TODO: template should take defaultServicePorts if ports is not defined
      ports:
      - 9080
    - hostname: details.mesh.global
      ports:
      - 9080
